-- select * from epadMedida;

insert into epadMedida(cdMedida, sgMedida, deMedida) values (1,'Ampola','Ampola');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (2,'Balde','Balde');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (3,'Bandej','Bandeja');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (4,'Barra','Barra');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (5,'Bisnag','Bisnaga');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (6,'Bloco','Bloco');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (7,'Bobina','Bobina');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (8,'Bomb','Bombona');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (9,'Caps','Capsula');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (10,'Cart','Cartela');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (11,'Cento','Cento');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (12,'Cj','Conjunto');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (13,'Cm','Centimetro');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (14,'Cm2','Centimetro Quadrado');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (15,'Cx','Caixa');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (16,'Cx2','Caixa Com 2 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (17,'Cx3','Caixa Com 3 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (18,'Cx5','Caixa Com 5 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (19,'Cx10','Caixa Com 10 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (20,'Cx15','Caixa Com 15 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (21,'Cx20','Caixa Com 20 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (22,'Cx25','Caixa Com 25 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (23,'Cx50','Caixa Com 50 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (24,'Cx100','Caixa Com 100 Unidades');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (25,'Disp','Display');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (26,'Duzia','Duzia');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (27,'Embal','Embalagem');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (28,'Fardo','Fardo');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (29,'Folha','Folha');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (30,'Frasco','Frasco');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (31,'Galao','Galão');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (32,'Gf','Garrafa');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (33,'Gramas','Gramas');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (34,'Jogo','Jogo');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (35,'Kg','Quilograma');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (36,'Kit','Kit');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (37,'Lata','Lata');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (38,'Litro','Litro');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (39,'M','Metro');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (40,'M2','Metro Quadrado');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (41,'M3','Metro Cúbico');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (42,'Milhei','Milheiro');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (43,'Ml','Mililitro');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (44,'Mwh','Megawatt Hora');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (45,'Pacote','Pacote');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (46,'Palete','Palete');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (47,'Pares','Pares');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (48,'Pc','Peça');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (49,'Pote','Pote');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (50,'K','Quilate');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (51,'Resma','Resma');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (52,'Rolo','Rolo');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (53,'Saco','Saco');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (54,'Sacola','Sacola');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (55,'Tambor','Tambor');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (56,'Tanque','Tanque');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (57,'Ton','Tonelada');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (58,'Tubo','Tubo');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (59,'Unid','Unidade');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (60,'Vasil','Vasilhame');
insert into epadMedida(cdMedida, sgMedida, deMedida) values (61,'Vidro','Vidro');
